"""
Converts chess_model.tflite → chess_model_data.h
A C array included directly in the Arduino sketch.
No PROGMEM — data goes into .rodata in the app partition (fits in 7.94MB).

Run: python tflite_to_header.py
"""
import os

TFLITE = r"G:\ChessAI\LichessEvaluations\esp32_model\chess_model.tflite"
HEADER = r"G:\ChessAI\LichessEvaluations\chess_inference_demo\chess_model_data.h"

with open(TFLITE, "rb") as f:
    data = f.read()

size = len(data)
print(f"Input : {TFLITE}")
print(f"Size  : {size:,} bytes ({size/1e6:.2f} MB)")
print(f"Source will be ~{size*6/1e6:.0f} MB of text but compiles back to {size/1e6:.2f} MB binary")

lines = [
    "// Auto-generated by tflite_to_header.py — do not edit manually",
    f"// Source: chess_model.tflite  ({size} bytes / {size/1e6:.2f} MB)",
    "// Note: source file is large but compiled binary = original tflite size",
    "",
    "#pragma once",
    "#include <stdint.h>",
    "",
    f"const unsigned int chess_model_tflite_len = {size};",
    "",
    "// No PROGMEM — stored in .rodata within the app partition",
    "const uint8_t chess_model_tflite[] = {",
]

row = []
for i, byte in enumerate(data):
    row.append(f"0x{byte:02x}")
    if len(row) == 12:
        lines.append("  " + ", ".join(row) + ",")
        row = []
if row:
    lines.append("  " + ", ".join(row))

lines += ["};", ""]

with open(HEADER, "w") as f:
    f.write("\n".join(lines))

print(f"Output: {HEADER}")
print("Done — add chess_model_data.h to your sketch folder and #include it")
